title: Advanced Machine Learning
description: GANs (Generative Adversarial Networks)
baseurl: "/AML_Tutorial_GANs"
url: "https://rajatsharma2204.github.io"
theme-dark: false
github_usernames: [adityagupta1089, rajatsharma2204]
plugins: [kramdown]
markdown: kramdown
